### ISSUE TITLE
Pibrella setup guide

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/hamster-party-cam#10]
The link to the Pibrella setup guide on the Hardware Information page is dead. I linked to the setup guide on the [Pibrella](http://pibrella.com/#setup) website: I hope this is ok, but, if not, can you point me at the new setup instructions location on Github, as I couldn't find it. Thanks!

**Comment by MissPhilbin** [comment]
Thanks, will eventually be replaced by our own guide.

**Comment by LornaLynch** [comment]
Thanks!
