### ISSUE TITLE
House style query

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/hamster-party-cam#11]
From a style point of view, are we happy for the final step in the worksheet to be "Community" rather than "What Next"?

**Comment by bennuttall** [comment]
"Community" is an oddity - it's used in two or three resources to credit where the idea came from, or similar. I think it should be part of the template somehow, rather than thrown in to the worksheet or somewhere.

**Comment by lawsie** [comment]
This is no longer the case, so closing the issue.
