### ISSUE TITLE
Poster image not displaying

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/hamster-party-cam#15]
It looks fine on Github, but it isn't showing on https://www.raspberrypi.org/learning/hamster-party-cam/ (under the "Community" header)

**Comment by lawsie** [comment]
Yeah, that's a weird one. I've re-saved it as a png in the hope that it's just a slightly dodgy file. We'll see in the next server pull through whether that's worked! Thanks for all the corrections :)

**Comment by lurch** [comment]
If it doesn't work, maybe it's something @bennuttall needs to have a quick look at?

**Comment by lurch** [comment]
Yeah, image still isn't displaying. However I've had a poke-around, and it looks like this is a bug in the script the converts the Github markdown files into the HTML files on the resources website.

In [worksheet.md](https://github.com/raspberrypilearning/hamster-party-cam/blob/master/worksheet.md) on github we have an image referenced as `![](images/wires.jpg)` and on the [corresponding resources page](https://www.raspberrypi.org/learning/hamster-party-cam/worksheet/) this gets converted to `<p><img src="../images/wires.jpg" alt="" /></p>`. The relative-URL rules get applied, and this means the image-url ends up as `https://www.raspberrypi.org/learning/hamster-party-cam/images/wires.jpg`, which [works fine](https://www.raspberrypi.org/learning/hamster-party-cam/images/wires.jpg).

However in [overview.md](https://github.com/raspberrypilearning/hamster-party-cam/blob/master/overview.md) on github we have an image referenced as `![Original poster idea](images/poster.png)` and on the [corresponding resources page](https://www.raspberrypi.org/learning/hamster-party-cam/) this gets converted to `<p><img src="../images/poster.png" alt="Original poster idea" /></p>`. When the relative-URL rules get applied, this then ends up as `https://www.raspberrypi.org/learning/images/poster.png` which [doesn't work](https://www.raspberrypi.org/learning/images/poster.png).

So the fix is for the script that converts the github-markdown into resources-html to be aware of what URL the destination page ends up at, and then apply the correct number of relative-URL steps when converting the image links.
In this example, https://www.raspberrypi.org/learning/hamster-party-cam/ should actually be linking to `<p><img src="./images/poster.png" alt="Original poster idea" /></p>` (note one dot instead of two!) which would then [correctly](https://www.raspberrypi.org/learning/hamster-party-cam/images/poster.png) resolve to `https://www.raspberrypi.org/learning/hamster-party-cam/images/poster.png`.

**Comment by lawsie** [comment]
Cheers, have raised it for our engineering team to have a look at.

**Comment by LornaLynch** [comment]
I've moved the Community section into the beginning of the main worksheet, and I've tweaked the text a little so that the quote from Violet falls with the poster image and doesn't seem out of context. Everything seems to be displaying now.
