### ISSUE TITLE
"Option 1" switch in the worksheet doesn't make sense

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/hamster-party-cam#7]
For an electrical switch to work there needs to be two wires - one for the 'electricity in' and one for the 'electricity out'.
However the "Option 1" switch in the worksheet shows one wire being connected to the bars of the hamster cage, with no second wire connected anywhere?!  I wonder if some extra steps have accidentally been deleted or left out?

**Comment by MissPhilbin** [comment]
Perhaps the terminology is wrong, but these instructions work. Any suggestions?

**Comment by lurch** [comment]
From the instructions provided, I'm not even sure how it works?
In the picture for Option 1 Step 2 you've got a red crocodile clip and a black crocodile clip. In the picture for Option 1 Step 3 you connect the other end of the red crocodile clip to the hamster-cage, but there's no indication where the other end of the black crocodile clip connects to?

**Comment by MissPhilbin** [comment]
I see what you are getting at. I'll add more info. The black cable is ground, so I guess I held it like a makey makey. It's been a while since I wrote this!

**Comment by lawsie** [comment]
Resource has been updated to use Explorer Hat so this issue is resolved.
