### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/hamster-party-cam#8]
- [x] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [x] hardware.yml
- [x] software.yml
- [x] extras.yml
- [x] overview.md
- [x] learn.md

**Comment by MissPhilbin** [comment]
component images required: crocodile clips, wind anemometer. Thanks @bennuttall

**Comment by bennuttall** [comment]
Hardware page says "speakers" but image references the headphones/speakers. If it's definitely just speakers that's fine as there will be a speakers-only image added.

**Comment by MissPhilbin** [comment]
Speakers only image prefered.

**Comment by bennuttall** [comment]
Crocodile clips added, wind sensor will be done tomorrow

**Comment by bennuttall** [comment]
Added wind speed sensor
